from typing import Any, Generic, TypeVar, Callable

class QObject: ...

T = TypeVar("T")

# 模拟信号类，支持索引语法
class Signal(Generic[T]):
    def connect(self, slot: Callable[[T], Any]) -> None: ...
    def emit(self, *args: T) -> None: ...
    def disconnect(self, slot: Callable[[T], Any]) -> None: ...